# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ccfa0924bc20d6498f7b97054a3e8a186c4cd342e1ca0e67d59214720514501460c3b3b8f081083e72aa2bdf2878503fd829bbc1deb141c71076fd531441fc2

test:
  secret_key_base: e96c5e4c3fbdcd0446154dc4c07204d2b4c862d8f881a1c18964258d7d348f3a4e90b24260918181e94640f1591c34e2da28fc625a572f42887c48d59dffd944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
